### ISSUE TITLE
Question about the reason for separating ELK stack

### ISSUE THREAD

**Issue by kyvaith** [million12/docker-kibana4#1]
Why Elasticsearch, Logstash, and Kibana are provided here as a separated containers, and not as ELK stack? It should be stacked IMO.

**Comment by pozgo** [comment]
Hi @kyvaith, 

There is always more than one approach to ELK :) Some people prefer to have everything in one package and some prefer in separate packages. Kind of hard to make everyone happy. 

There are few reasons actually:
1. Docker image is meant to do just one task and one task only.  
2. Versioning
3. Scalability.

PS. You can always create `docker-cloud.yml` for whole ELK stack and run it with one command.
